#include "kryon.h"
#include "ide/state.h"
#include "native_internal.h"
#include "app_host.h"
#include "kry_dylib.h"

#include <dirent.h>
#include <errno.h>
#include <ctype.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

static int
krait_mkdir_p(const char *dir)
{
    char tmp[KRAIT_PATH_MAX];
    size_t len;

    if(dir == NULL || dir[0] == '\0')
        return 0;
    snprintf(tmp, sizeof(tmp), "%s", dir);
    len = strlen(tmp);
    if(len > 0 && tmp[len - 1] == '/')
        tmp[len - 1] = '\0';
    for(char *p = tmp + 1; *p != '\0'; p++) {
        if(*p == '/') {
            *p = '\0';
            if(mkdir(tmp, 0755) != 0 && errno != EEXIST)
                return 0;
            *p = '/';
        }
    }
    if(mkdir(tmp, 0755) != 0 && errno != EEXIST)
        return 0;
    return 1;
}

int
krait_scaffold_project(const char *dir, char *status, int status_size)
{
    char project_kryon[KRAIT_PATH_MAX];
    char main_kry[KRAIT_PATH_MAX];
    char makefile_path[KRAIT_PATH_MAX];
    char name[96];
    char project_file[256];
    char makefile_contents[4096];
    const char *kryon_dir;
    const char *main_kry_contents =
        "#import \"kryon.h\"\n"
        "\n"
        "app \"New Kryon App\" {\n"
        "    size 800 600\n"
        "    fps 60\n"
        "    theme THEME_MONO light\n"
        "}\n"
        "\n"
        "state {\n"
        "    click_count: int = 0\n"
        "}\n"
        "\n"
        "screen Main(viewport: Rectangle) {\n"
        "    Background(GetThemeBackground())\n"
        "    Text(\"Hello, Kryon!\", ScaleUIPx(20), ScaleUIPx(20), UI_TEXT_24, GetThemeText())\n"
        "    Text(\"Edit main.kry and the canvas reloads.\", ScaleUIPx(20), ScaleUIPx(54), UI_TEXT_16, GetThemeIcon())\n"
        "    if Button((ButtonProps){\n"
        "        .bounds = {ScaleUIPx(20), ScaleUIPx(100), ScaleUIPx(160), ScaleUIPx(40)},\n"
        "        .label = \"Click me\",\n"
        "        .style = UI_BUTTON_STYLE_PRIMARY,\n"
        "    }) {\n"
        "        click_count++\n"
        "    }\n"
        "    Text(TextFormat(\"Clicks: %d\", click_count), ScaleUIPx(20), ScaleUIPx(160), UI_TEXT_16, GetThemeText())\n"
        "}\n";

    if(dir == NULL || dir[0] == '\0') {
        if(status != NULL && status_size > 0)
            snprintf(status, (size_t)status_size, "Cannot scaffold: no directory");
        return 0;
    }
    snprintf(name, sizeof(name), "%s", krait_basename(dir));
    if(!krait_mkdir_p(dir)) {
        if(status != NULL && status_size > 0)
            snprintf(status, (size_t)status_size,
                     "Cannot create project directory: %s", dir);
        return 0;
    }
    krait_join(project_kryon, sizeof(project_kryon), dir, "project.kryon");
    snprintf(project_file, sizeof(project_file),
             "# Generated by Krait. Edit targets and metadata here.\n"
             "name \"%s\"\n",
             name);
    if(!krait_write_text_file(project_kryon, project_file)) {
        if(status != NULL && status_size > 0)
            snprintf(status, (size_t)status_size, "Cannot write %s",
                     project_kryon);
        return 0;
    }
    krait_join(main_kry, sizeof(main_kry), dir, "main.kry");
    if(!krait_write_text_file(main_kry, main_kry_contents)) {
        if(status != NULL && status_size > 0)
            snprintf(status, (size_t)status_size, "Cannot write %s", main_kry);
        return 0;
    }
    kryon_dir = getenv("KRYON_DIR");
    if(kryon_dir == NULL || kryon_dir[0] == '\0')
        kryon_dir = "/usr/home/wao/src/krait/vendor/kryon";
    snprintf(makefile_contents, sizeof(makefile_contents),
             "CC ?= cc\n"
             "KRYON_DIR ?= %s\n"
             "BUILD_DIR ?= build/kryon\n"
             "KRY_SRCS := $(wildcard *.kry)\n"
             "KC := $(KRYON_DIR)/build/bin/kc\n"
             "\n"
             ".PHONY: all clean\n"
             "\n"
             "all: $(BUILD_DIR)/.transpiled\n"
             "\n"
             "$(KC):\n"
             "\t$(MAKE) -C $(KRYON_DIR) all\n"
             "\n"
             "$(BUILD_DIR)/.transpiled: $(KRY_SRCS) | $(KC)\n"
             "\t@mkdir -p $(BUILD_DIR)\n"
             "\t$(KC) --root . -o $(BUILD_DIR) $(KRY_SRCS)\n"
             "\t@touch $@\n"
             "\n"
             "clean:\n"
             "\trm -rf build\n",
             kryon_dir);
    krait_join(makefile_path, sizeof(makefile_path), dir, "Makefile");
    if(!krait_write_text_file(makefile_path, makefile_contents)) {
        if(status != NULL && status_size > 0)
            snprintf(status, (size_t)status_size, "Cannot write %s",
                     makefile_path);
        return 0;
    }
    if(status != NULL && status_size > 0)
        snprintf(status, (size_t)status_size, "Scaffolded project at %s", dir);
    return 1;
}

