#include "kryon.h"
#include "ide/state.h"
#include "native_internal.h"
#include "app_host.h"
#include "kry_dylib.h"

#include <dirent.h>
#include <errno.h>
#include <ctype.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

int
krait_mkdir_p(const char *dir)
{
    char tmp[KRAIT_PATH_MAX];
    size_t len;

    if(dir == NULL || dir[0] == '\0')
        return 0;
    snprintf(tmp, sizeof(tmp), "%s", dir);
    len = strlen(tmp);
    if(len > 0 && tmp[len - 1] == '/')
        tmp[len - 1] = '\0';
    for(char *p = tmp + 1; *p != '\0'; p++) {
        if(*p == '/') {
            *p = '\0';
            if(mkdir(tmp, 0755) != 0 && errno != EEXIST)
                return 0;
            *p = '/';
        }
    }
    if(mkdir(tmp, 0755) != 0 && errno != EEXIST)
        return 0;
    return 1;
}

int
krait_scaffold_project(const char *dir, char *status, int status_size)
{
    char project_kryon[KRAIT_PATH_MAX];
    char main_kry[KRAIT_PATH_MAX];
    char game_scene[KRAIT_PATH_MAX];
    char makefile_path[KRAIT_PATH_MAX];
    char name[96];
    char project_file[256];
    char makefile_contents[4096];
    const char *kryon_dir;
    char kryon_dir_buf[KRAIT_PATH_MAX];
    const char *main_kry_contents =
        "#import \"kryon.h\"\n"
        "\n"
        "app \"New Kryon App\" {\n"
        "    size 800 600\n"
        "    fps 60\n"
        "    theme THEME_MONO light\n"
        "}\n"
        "\n"
        "state {\n"
        "    click_count: int = 0\n"
        "}\n"
        "\n"
        "Main :: () #ui {\n"
        "    Screen root: {\n"
        "    Background(GetThemeBackground())\n"
        "    Text(\"Hello, Kryon!\", ScaleUIPx(20), ScaleUIPx(20), ScaleUIPx(24), GetThemeText())\n"
        "    Text(\"Edit main.kry and the canvas reloads.\", ScaleUIPx(20), ScaleUIPx(54), ScaleUIPx(16), GetThemeIcon())\n"
        "    if Button((ButtonProps){\n"
        "        .bounds = {ScaleUIPx(20), ScaleUIPx(100), ScaleUIPx(160), ScaleUIPx(40)},\n"
        "        .label = \"Click me\",\n"
        "        .style = ButtonStylePrimary,\n"
        "    }) {\n"
        "        click_count++\n"
        "    }\n"
        "    Text(TextFormat(\"Clicks: %d\", click_count), ScaleUIPx(20), ScaleUIPx(160), ScaleUIPx(16), GetThemeText())\n"
        "    }\n"
        "}\n";
    /* Starter game scene for the Game Engine mode: a tiny platformer with
     * collectible coins, a win exit and a score timer, all wired through
     * the trigger system. Same format krait_engine_load() reads. */
    const char *game_scene_contents =
        "# krait game scene 1\n"
        "name \"Main\"\n"
        "gravity 0 980\n"
        "view 640 360\n"
        "node 1 0 Body2D \"Ground\"\n"
        "x 320\n"
        "y 332\n"
        "size 640 56\n"
        "body static\n"
        "shape box\n"
        "\n"
        "node 2 0 Body2D \"Platform\"\n"
        "x 180\n"
        "y 232\n"
        "size 160 16\n"
        "body static\n"
        "shape box\n"
        "\n"
        "node 3 0 Body2D \"Player\"\n"
        "x 80\n"
        "y 280\n"
        "behavior player\n"
        "size 28 44\n"
        "body dynamic\n"
        "fixed_rot 1\n"
        "shape box\n"
        "color 240 150 60 255\n"
        "\n"
        "node 4 0 Area2D \"Coin\"\n"
        "x 260\n"
        "y 180\n"
        "size 24 24\n"
        "shape circle\n"
        "color 240 200 60 255\n"
        "trigger collect\n"
        "\n"
        "node 5 0 Area2D \"Coin2\"\n"
        "x 420\n"
        "y 120\n"
        "size 24 24\n"
        "shape circle\n"
        "color 240 200 60 255\n"
        "trigger collect\n"
        "\n"
        "node 6 0 Area2D \"Exit\"\n"
        "x 560\n"
        "y 300\n"
        "size 48 48\n"
        "shape box\n"
        "color 120 220 140 255\n"
        "trigger win\n"
        "\n"
        "node 7 0 Timer \"ScoreTicker\"\n"
        "timer 1 1 1\n"
        "trigger score\n"
        "\n"
        "node 8 0 AnimationPlayer \"FloatAnim\"\n"
        "anim 1 1 1\n"
        "atrack \"Coin2\" posy 2\n"
        "akey 0 120\n"
        "akey 1.5 90\n"
        "\n"
        "node 9 0 Camera2D \"Camera\"\n"
        "x 320\n"
        "y 180\n"
        "camera 1 1\n"
        "\n";

    if(dir == NULL || dir[0] == '\0') {
        if(status != NULL && status_size > 0)
            snprintf(status, (size_t)status_size, "Cannot scaffold: no directory");
        return 0;
    }
    snprintf(name, sizeof(name), "%s", krait_basename(dir));
    if(!krait_mkdir_p(dir)) {
        if(status != NULL && status_size > 0)
            snprintf(status, (size_t)status_size,
                     "Cannot create project directory: %s", dir);
        return 0;
    }
    krait_join(project_kryon, sizeof(project_kryon), dir, "project.kryon");
    snprintf(project_file, sizeof(project_file),
             "# Generated by Krait. Edit targets and metadata here.\n"
             "name \"%s\"\n",
             name);
    if(!krait_write_text_file(project_kryon, project_file)) {
        if(status != NULL && status_size > 0)
            snprintf(status, (size_t)status_size, "Cannot write %s",
                     project_kryon);
        return 0;
    }
    krait_join(main_kry, sizeof(main_kry), dir, "main.kry");
    if(!krait_write_text_file(main_kry, main_kry_contents)) {
        if(status != NULL && status_size > 0)
            snprintf(status, (size_t)status_size, "Cannot write %s", main_kry);
        return 0;
    }
    krait_join(game_scene, sizeof(game_scene), dir, "game.scene");
    if(!krait_write_text_file(game_scene, game_scene_contents)) {
        if(status != NULL && status_size > 0)
            snprintf(status, (size_t)status_size, "Cannot write %s", game_scene);
        return 0;
    }
    krait_kryon_dir(kryon_dir_buf, sizeof(kryon_dir_buf));
    kryon_dir = kryon_dir_buf;
    snprintf(makefile_contents, sizeof(makefile_contents),
             "CC ?= cc\n"
             "KRYON_DIR ?= %s\n"
             "BUILD_DIR ?= build/kryon\n"
             "KRY_SRCS := $(wildcard *.kry)\n"
             "KRYON_PLATFORM := $(shell uname -s)\n"
             "ifeq ($(KRYON_PLATFORM),Linux)\n"
             "KRYON_PLATFORM := linux\n"
             "else ifeq ($(KRYON_PLATFORM),FreeBSD)\n"
             "KRYON_PLATFORM := freebsd\n"
             "else ifeq ($(KRYON_PLATFORM),Darwin)\n"
             "KRYON_PLATFORM := macos\n"
             "endif\n"
             "KRYON_ARCH := $(shell uname -m)\n"
             "ifeq ($(KRYON_ARCH),amd64)\n"
             "KRYON_ARCH := x86_64\n"
             "endif\n"
             "K2C := $(KRYON_DIR)/build/$(KRYON_PLATFORM)-$(KRYON_ARCH)/bin/k2c\n"
             "\n"
             ".PHONY: all clean\n"
             "\n"
             "all: $(BUILD_DIR)/.transpiled\n"
             "\n"
             "$(K2C):\n"
             "\t$(MAKE) -C $(KRYON_DIR) all\n"
             "\n"
             "$(BUILD_DIR)/.transpiled: $(KRY_SRCS) | $(K2C)\n"
             "\t@mkdir -p $(BUILD_DIR)\n"
             "\t$(K2C) --root . -o $(BUILD_DIR) $(KRY_SRCS)\n"
             "\t@touch $@\n"
             "\n"
             "clean:\n"
             "\trm -rf build\n",
             kryon_dir);
    krait_join(makefile_path, sizeof(makefile_path), dir, "Makefile");
    if(!krait_write_text_file(makefile_path, makefile_contents)) {
        if(status != NULL && status_size > 0)
            snprintf(status, (size_t)status_size, "Cannot write %s",
                     makefile_path);
        return 0;
    }
    if(status != NULL && status_size > 0)
        snprintf(status, (size_t)status_size, "Scaffolded project at %s", dir);
    return 1;
}
